Repository openfisca/fr.openfisca.org, pull requests merged in 2018-04, with the labels that each got.

#9 Change link to new legislation explorer
  CHANGELOG.md
  pages/index.js
Labels: flow:team:doing, kind:improvement, note:packaging

#7 Specify node version
  README.md
  package.json
Labels: flow:team:doing, kind:documentation

#10 Ajout le déploiement continu du site
  CHANGELOG.md
  circle.yml
  deploy.sh
  package.json
Labels: flow:team:doing
